config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  draw :admin
  draw :dashboard

  devise_for :users, controllers: { sessions: 'users/sessions', confirmations: 'users/confirmations' }
  as :user do
    get '/dashboard/profile',      to: 'users/sessions#profile'
    get '/dashboard/profile/edit', to: 'users/sessions#edit'
    put '/dashboard/profile/edit', to: 'users/sessions#update'
  end

  root to: 'pages#index'
  get '/about' => 'pages#about'
  get '/help' => 'pages#help'
  get '/tos' => 'pages#tos'
  get '/privacy' => 'pages#privacy'
  get '/search' => 'pages#search'
  get '/subscribe' => 'pages#subscribe'
  get '/jobs' => 'pages#jobs'

  devise_scope :user do
    get 'auth/facebook/callback',  to: 'users/sessions#create'
    get 'auth/failure',            to: redirect('/')
  end

  resources :cities

  resources :visa_types do
    resources :visa_requirements, except: [:show]
  end

  resources :jobs, only: [:search] do
    get '/search' => 'jobs#search', on: :collection
  end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
end

app/views/layouts/shared/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if yield(:title).present? %>
        <%= "#{yield(:title)} | " %> SimpleSettler
    <% else %>
        SimpleSettler
    <% end %>
  </title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name='description'
        content='<%= yield_meta_tag(:description, 'SimpleSettler, one stop hub for your people looking to migrate.') %>'/>
  <meta name='keywords'
        content='<%= yield_meta_tag(:keywords, 'student visas,migrant accomodation,settlement help') %>'/>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag 'favicon.png', rel: 'shortcut icon', type: 'image/png' %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
  <%= javascript_include_tag 'application' %>

  <%= cloudinary_js_config %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <script src="http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/a549aa8780dbda16f6cff545aeabc3d71073911e/src/js/bootstrap-datetimepicker.js"></script>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/a549aa8780dbda16f6cff545aeabc3d71073911e/build/css/bootstrap-datetimepicker.css" rel="stylesheet"/>


  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>


<body class="dashboard">
<nav class="navbar navbar-ss navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu-content" aria-expanded="false" aria-controls="navbar">
        <!--<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">-->
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="navbar-collapse collapse">

      <div class="nav navbar-nav navbar-left">
          <div class="dropdown">
            <%= image_tag('logo.png', title: 'simplesettler', alt: 'simplesettler', class: 'dropdown', data: {toggle: 'dropdown'}, role: 'button', aria: {haspopop: true, expanded: false}) %>
            <ul class="dropdown-menu dropdown-menu-left hidden-xs">

              <li><%= link_to "Visit Website", root_path %>
              </li>

              <li><%= link_to "Dashboard", dashboard_root_path %>
              </li>
            </ul>
          </div>
      </div>


      <ul class="nav navbar-right ">

        <li class="dropdown">
          <a href="#" class="hidden-xs dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <div class="profile menu-head-title">
              <span>
            <%= image_tag('default.png', class: ' hidden-xs img-circle profile-image', title: 'simplesettler', alt: 'simplesettler') %>
              </span>
              <span class="pp-name">
                  <%= current_user.full_name || current_user.username %>
                </span>
            </div>
          </a>
          <ul class="dropdown-menu dropdown-menu-left hidden-xs">

            <li><%= link_to "Logout", destroy_user_session_path, method: 'delete', class: "logoutButton " %>
            </li>

            <li><%= link_to "Profile", dashboard_profile_path %>
            </li>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<!-- <div class="container-fluid dashboard-content"> -->
  <div class="row dashboard-content">
    <div class="col-md-1 no-padding">

      <div class="nav-side-menu">
        <!--<div class="brand">Brand Logo</div>-->


        <div class="menu-list">
          <ul id="menu-content" class="menu-content collapse out">
            <li class='<%= controller_name=="visas"  ? "active" : "" %>'>
              <%= link_to(dashboard_visas_path) do %>
                  <i class="fa fa-dashboard fa-3x"></i>
                  <div class="menu-head-title"><span class="menu-head-title">Visa Dashboard</span></div>
              <% end %>
            </li>

            <li class="<%= controller_name=="consultations" ? "active" : "" %>">
              <%= link_to(dashboard_consultations_path) do %>
                  <i class="fa fa-users fa-3x" aria-hidden="true"></i>
                  <div class="menu-head-title"><span>Request a Consultation</span></div>
              <% end %>
            </li>
            <li class="<%= controller_name=="faqs" ? "active" : "" %>">
              <a href="#">
                <%= link_to(dashboard_faqs_path) do %>
                    <i class="fa fa-question-circle-o fa-3x" aria-hidden="true"></i>
                    <div class="menu-head-title"><span>FAQ</span></div>
                    <% end %>
              </a>
            </li>

            <li>
              <a href="#">
                <i class="fa fa-volume-control-phone fa-3x" aria-hidden="true"></i>
                <div class="menu-head-title"><span>Call AU Hotline</span></div>
              </a>
            </li>
            <li class="visible-xs">
              <%= link_to(destroy_user_session_path, method: 'delete') do %>
                  <i class="fa fa-sign-out fa-3x" aria-hidden="true"></i>
                  <div class="menu-head-title"><span>Logout</span></div>
              <% end %>
            </li>
            <li class="visible-xs">
              <%= link_to(dashboard_profile_path) do %>
                  <i class="fa fa-user fa-3x" aria-hidden="true"></i>
                  <div class="menu-head-title"><span>Profile</span></div>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    </div>

    <!--
    <div class="col-md-2 left-sub-menu">
      <ul class="sub-menu">
        <a>
          <li class="active">SELECT VISA</li>
          <span class="arrow"></span></a>
        <a>
          <li>HOW IT WORKS</li>
          <span class="arrow"></span></a>
      </ul>
    </div>-->

    <div class="col-md-11 content-section">
      <div class="row">


        <div class="col-md-8 col-md-offset-2">
          <% if controller_name=="dashboard" && (controller.action_name!="index" && controller.action_name!="request_consultation") %>
              <div class="row">
                <div class="col-md-12 text-center">
                  <h3><%= defined?(@visa_type) ? @visa_type[:name] : @visa_help_type[:name] %></h3>
                </div>

                <div class="col-md-12">
                  <ul id="progressbar">
                    <li class="<%= (defined?(@current_step) && @current_step >=1) ? 'active' : '' %>">Requirements</li>
                    <li class="<%= (defined?(@current_step) && @current_step >=2) ? 'active' : '' %>">Applicant
                      Details
                    </li>
                    <li class="<%= (defined?(@current_step) && @current_step >=3) ? 'active' : '' %>">Diy + Agent
                      Review
                    </li>
                    <li class="<%= (defined?(@current_step) && @current_step >=4) ? 'active' : '' %>">Submit</li>
                  </ul>
                </div>
              </div>

          <% end %>

          <div class="row">

            <% flash.each do |name, message| %>
                <div class="alert alert-<%= name %>" role="alert">
                  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                  <span class="sr-only"><%= name.to_s.capitalize %>:</span>
                  <%= message %>
                </div>
            <% end %>
          </div>
          <div class="row">
            <%= yield %>
          </div>
        </div>

      </div>

    </div>
  </div>

<!-- </div> -->
</body>
</html>

app/views/layouts/shared/metatags.html.erb
<title><%= yield(:title).presence || "Default title" %></title>
<meta name="keywords" content="<%= yield(:meta_keywords).presence || "default, keywords" %>" />
<meta name="description" content="<%= yield(:meta_description).presence || "Default description" %>" />
<meta name="author" content="<%= yield(:meta_author).presence || "Default Author" %>" />