config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  draw :admin
  draw :dashboard

  devise_for :users, controllers: { sessions: 'users/sessions', confirmations: 'users/confirmations' }
  as :user do
    get '/dashboard/profile',      to: 'users/sessions#profile'
    get '/dashboard/profile/edit', to: 'users/sessions#edit'
    put '/dashboard/profile/edit', to: 'users/sessions#update'
  end

  root to: 'pages#index'
  get '/about' => 'pages#about'
  get '/help' => 'pages#help'
  get '/tos' => 'pages#tos'
  get '/privacy' => 'pages#privacy'
  get '/search' => 'pages#search'
  get '/subscribe' => 'pages#subscribe'
  get '/jobs' => 'pages#jobs'

  devise_scope :user do
    get 'auth/facebook/callback',  to: 'users/sessions#create'
    get 'auth/failure',            to: redirect('/')
  end

  resources :cities

  resources :visa_types do
    resources :visa_requirements, except: [:show]
  end

  resources :jobs, only: [:search] do
    get '/search' => 'jobs#search', on: :collection
  end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
end

app/views/shared/_footer.html.erb
<footer>
  <div class="footer" id="footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-4  col-md-4 col-sm-4 col-xs-12">
          <h4><%= t('site.footer.company.title') %></h4>
          <ul>
            <li><%= link_to t('site.footer.company.home'), root_path %></li>
            <li><%= link_to t('site.footer.company.about'), about_path %></li>
            <li><%= link_to t('site.footer.support.tos'), tos_path %></li>
            <li><%= link_to t('site.nav.jobs'), jobs_path %></li>
            <li><%= link_to t('site.nav.help'), '/dashboard', class: "primary-btn ss-button" %></li>
          </ul>
        </div>
        <div class="col-lg-4  col-md-4 col-sm-4 col-xs-12">
          <h4><%= t('site.footer.subscribe.label') %></h4>
          <ul>
            <li class="ss-input-container subscribe">
              <%= form_tag '/subscribe', id: 'subscribe' do %>
                <%= text_field_tag :email, nil, class: 'ss-input', :placeholder => t('site.footer.subscribe.placeholder') %>
                <%= button_tag(type: 'submit') do %>
                  <i class="fa fa-paper-plane"></i>
                <% end %>
              <% end %>
            </li>
          </ul>
        </div>
        <div class="col-lg-4  col-md-4 col-sm-4 col-xs-12">
          <h4><%= t('site.footer.subscribe.follow') %></h4>
          <ul class="social">
            <li>
              <%= link_to("https://www.facebook.com/simplesettler", target: '_blank') do %>
                <i class="fa fa-facebook-square" aria-hidden="true"></i>
              <% end %>
            </li>
            <li>
              <%= link_to("https://twitter.com/simplesettler", target: '_blank') do %>
                <i class="fa fa-twitter" aria-hidden="true"></i>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <div class="row">
        <hr class="footer-divider">
        <div class="col-sm-12">
          <div class="footer-disclaimer">
            <a style="font-size: 13px;" href="/privacy">Privacy Policy</a><span> | Copyright © 2017 SimpleSettler</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>
<script>
$(function(){
  $('#subscribe').on('submit', function(e){
    e.preventDefault();
    var email_address = $('#subscribe > #email').val();
    $.ajax({
      method: "GET",
      header: 'content-type: application/json',
      url: "/subscribe?email=" + email_address,
      success: function(data) {
        $('.subscribe').html('<div>'+ data['message']+'</div>');
      },
      error: function (data) {
        $('#subscribe').append('<div>'+ data.responseJSON.error + '</div>');
      }
    });
  });
})
</script>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top shadow-bottom">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to(root_path) do %>
        <%= image_tag('logo.png', title: 'simplesettler', alt: 'simplesettler', class: 'logo') %>
      <% end %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="ss-nav nav navbar-nav pull-right">
        <li><%= link_to t('site.nav.help'), dashboard_root_path, class: 'primary-btn ss-button' %></li>
        <li><%= link_to t('site.nav.jobs'), jobs_path %></li>
        <% unless current_user %>
          <li><%= link_to t('site.nav.login'), new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/shared/admin.js.erb
$('.articles tbody').html('<%= j render instance_variable_get("@#{controller_name.downcase}") %>');
$(this).siblings().removeClass("active");
$(this).addClass("active");

app/views/shared/destroy.js.erb
<% obj = instance_variable_get("@#{controller_name.singularize.downcase}") %>
$("#<%= dom_id(obj) %>").fadeOut(500, function() {
  $(this).remove();
});

app/views/shared/edit.html.erb
<%= render 'form' %>

app/views/shared/new.html.erb
<%= render 'form' %>